# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssowrap < Formula
  desc "ssowrap is a single binary tool that run a command using AWS SSO credentials."
  homepage "https://github.com/winebarrel/ssowrap"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ssowrap/releases/download/v0.1.3/ssowrap_0.1.3_darwin_amd64.tar.gz"
      sha256 "0d0e18acbebd6e10e4e1d298fc9eb1689366e40a5e9bbd43f05c13854e495905"

      def install
        bin.install 'ssowrap'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/ssowrap/releases/download/v0.1.3/ssowrap_0.1.3_darwin_arm64.tar.gz"
      sha256 "05901ea65f1e33091588109f88b9ab14a8a6a397fe322297b3df5c44e661d85c"

      def install
        bin.install 'ssowrap'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/ssowrap/releases/download/v0.1.3/ssowrap_0.1.3_linux_amd64.tar.gz"
        sha256 "a614147103356c547d9b98b86794bb9d6b31c47873ac6c4e1b2ec18f0fa0db87"

        def install
          bin.install 'ssowrap'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/ssowrap/releases/download/v0.1.3/ssowrap_0.1.3_linux_arm64.tar.gz"
        sha256 "b0a7bd58d1c0434e2b711c22bb3e8b6f1a8018915703390975e4f8cb7570fdc7"

        def install
          bin.install 'ssowrap'
        end
      end
    end
  end
end
